revert log mecanism

diff --git a/git-cclone b/git-cclone
--- a/git-cclone
+++ b/git-cclone
@@ -15,17 +15,8 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 
-# prefix log with cache server name
-log() {
-	srvid="git-cclone"
-	while IFS='' read -r line; do 
-		echo "$srvid $line" >&2
-	done
-}
-exec 2> >(log)
-
-error() { echo "ERROR: $*" >&2; exit 1; }
-info() { echo "INFO: $*" >&2; }
+error() { echo "git-cclone ERROR: $*" >&2; exit 1; }
+info() { echo "git-clone $*" >&2; }
 
 [[ -r ~/.gitcache.conf ]] && . ~/.gitcache.conf
 
@@ -43,12 +34,11 @@ crepo="${GIT_CACHE_SERVER}:$(ssh "$GIT_CACHE_SERVER" gitcache-server --clone "$r
 
 info "Upstream repository: $repo"
 info "Cache repository: $crepo"
-info "Cloning to local directory: $dir"
 
 git clone $mirror "$crepo" "$dir" >&2
 
 cd "$dir"
 git remote set-url --push origin "$repo" >&2
 git config remote.origin.uploadpack gitcache-server >&2
-info "done: cache server will be used for fetch operations"
+info "done. Git-cache is active for future fetch operations"
 
diff --git a/git-crecover b/git-crecover
--- a/git-crecover
+++ b/git-crecover
@@ -15,17 +15,8 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 
-# prefix log with cache server name
-log() {
-	srvid="git-crecover"
-	while IFS='' read -r line; do 
-		echo "$srvid $line" >&2
-	done
-}
-exec 2> >(log)
-
-error() { echo "ERROR: $*" >&2; exit 1; }
-info() { echo "INFO: $*" >&2; }
+error() { echo "git-crecover ERROR: $*" >&2; exit 1; }
+info() { echo "git-crecover $*" >&2; }
 
 [[ -r ~/.gitcache.conf ]] && . ~/.gitcache.conf
 
diff --git a/gitcache-server b/gitcache-server
--- a/gitcache-server
+++ b/gitcache-server
@@ -15,17 +15,10 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 
-# prefix log with cache server name
-log() {
-	srvid="git-cache($(id -un)@$(hostname -f))"
-	while IFS='' read -r line; do 
-		echo "$srvid $line" >&2
-	done
-}
-exec 2> >(log)
+srvid="gitcache-server($(id -un)@$(hostname -f))"
 
-error() { echo "ERROR: $*" >&2; exit 1; }
-info() { echo "INFO: $*" >&2; }
+error() { echo "$srvid ERROR: $*" >&2; exit 1; }
+info() { echo "$srvid $*" >&2; }
 
 [[ -r ~/.gitcache-server.conf ]] && . ~/.gitcache-server.conf
 
@@ -43,7 +36,7 @@ if [[ "$1" != "--clone" ]]; then
 fi
 
 uri=$(sed 's/ /%20/g' <<<$2)
-info "clone requested for $uri"
+info "clone request for $uri"
 
 if [[ $uri =~ ^(.+://)?(.+@)?([^:/]+)(:[0-9]+)?(/.+)$ ]]; then
     domain=${BASH_REMATCH[3]}
