added license; added prefix in programs outputs

diff --git a/git-cclone b/git-cclone
--- a/git-cclone
+++ b/git-cclone
@@ -1,7 +1,31 @@
 #!/bin/bash
 
-error() { echo "ERROR(git-cclone): $*" >&2; exit 1; }
-info() { echo "INFO(git-cclone): $*" >&2; }
+# Copyright 2013, Intel Inc.
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; version 2 of the License.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU Library General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+
+# prefix log with cache server name
+log() {
+	srvid="git-cclone"
+	while IFS='' read -r line; do 
+		echo "$srvid $line" >&2
+	done
+}
+exec 2> >(log)
+
+error() { echo "ERROR: $*" >&2; exit 1; }
+info() { echo "INFO: $*" >&2; }
 
 [[ -r ~/.gitcache.conf ]] && . ~/.gitcache.conf
 
@@ -17,14 +41,14 @@ info "asking $GIT_CACHE_SERVER a cache for $repo"
 crepo="${GIT_CACHE_SERVER}:$(ssh "$GIT_CACHE_SERVER" gitcache-server --clone "$repo")"
 [[ -z "$crepo" ]] && error "can't get a cache"
 
-info "cache for $repo is $crepo"
+info "Upstream repository: $repo"
+info "Cache repository: $crepo"
+info "Cloning to local directory: $dir"
 
-info "cloning $crepo into $dir"
 git clone $mirror "$crepo" "$dir" >&2
 
-info "init of git $dir"
 cd "$dir"
 git remote set-url --push origin "$repo" >&2
 git config remote.origin.uploadpack gitcache-server >&2
-info "done"
+info "done: cache server will be used for fetch operations"
 
diff --git a/git-crecover b/git-crecover
--- a/git-crecover
+++ b/git-crecover
@@ -1,7 +1,31 @@
 #!/bin/bash
 
-error() { echo "ERROR(git-crecover): $*" >&2; exit 1; }
-info() { echo "INFO(git-crecover): $*" >&2; }
+# Copyright 2013, Intel Inc.
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; version 2 of the License.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU Library General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+
+# prefix log with cache server name
+log() {
+	srvid="git-crecover"
+	while IFS='' read -r line; do 
+		echo "$srvid $line" >&2
+	done
+}
+exec 2> >(log)
+
+error() { echo "ERROR: $*" >&2; exit 1; }
+info() { echo "INFO: $*" >&2; }
 
 [[ -r ~/.gitcache.conf ]] && . ~/.gitcache.conf
 
@@ -14,17 +38,17 @@ do_recover() {
     crepo="${GIT_CACHE_SERVER}:$(ssh "$GIT_CACHE_SERVER" gitcache-server --clone "$repo")"
     [[ -z "$crepo" ]] && error "can't get a cache"
     info "init of git $dir"
-    git remote set-url origin "$crepo"
-    git remote set-url --push origin "$repo"
-    git config remote.origin.uploadpack gitcache-server
+    git remote set-url origin "$crepo" >&2
+    git remote set-url --push origin "$repo" >&2
+    git config remote.origin.uploadpack gitcache-server >&2
     info "done"
     exit 0
 }
 
 do_remove() {
     info "removing cache reference"
-    git config --unset remote.origin.uploadpack
-    git remote set-url origin "$repo"
+    git config --unset remote.origin.uploadpack >&2
+    git remote set-url origin "$repo" >&2
     info "done"
     exit 0
 }
diff --git a/gitcache-server b/gitcache-server
--- a/gitcache-server
+++ b/gitcache-server
@@ -1,7 +1,31 @@
 #!/bin/bash
 
-error() { echo "ERROR(gitcache-server): $*" >&2; exit 1; }
-info() { echo "INFO(gitcache-server): $*" >&2; }
+# Copyright 2013, Intel Inc.
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; version 2 of the License.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU Library General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+
+# prefix log with cache server name
+log() {
+	srvid="git-cache($(id -un)@$(hostname -f))"
+	while IFS='' read -r line; do 
+		echo "$srvid $line" >&2
+	done
+}
+exec 2> >(log)
+
+error() { echo "ERROR: $*" >&2; exit 1; }
+info() { echo "INFO: $*" >&2; }
 
 [[ -r ~/.gitcache-server.conf ]] && . ~/.gitcache-server.conf
 
@@ -11,9 +35,9 @@ if [[ "$1" != "--clone" ]]; then
 	shift $(($# - 1))
 	info "going to directory $1"
 	cd "$1" 2>/dev/null || error "directory not found $1"
-	info fetching
-	git fetch --progress
-	info uploading
+	info refreshing cache from $(git ls-remote --get-url origin)
+	git fetch --progress >&2
+	info uploading changes to client
 	git-upload-pack .
 	exit
 fi
@@ -25,7 +49,7 @@ if [[ $uri =~ ^(.+://)?(.+@)?([^:/]+)(:[0-9]+)?(/.+)$ ]]; then
     domain=${BASH_REMATCH[3]}
     project=${BASH_REMATCH[5]}
 #    info "sheme ${BASH_REMATCH[1]} user ${BASH_REMATCH[2]} domain ${BASH_REMATCH[3]} port ${BASH_REMATCH[4]} path ${BASH_REMATCH[5]}"
-elif [[ $uri =~ ^(.+@)?([^:]+):(.+)$ ]]; then
+elif [[ $uri =~ ^(.+@)?([^:/]+):(.+)$ ]]; then
     domain=${BASH_REMATCH[2]}
     project=${BASH_REMATCH[3]}
 #    info "sheme - user ${BASH_REMATCH[1]} domain ${BASH_REMATCH[2]} port - path ${BASH_REMATCH[3]}"
@@ -57,15 +81,15 @@ if [[ ! -d $gcdir ]]; then
     edir="$(basename $gcdir)"
     if [[ -n "$GIT_CACHE_SERVER_PRIMARY" ]]; then
 		export GIT_CACHE_SERVER="$GIT_CACHE_SERVER_PRIMARY"
-		info "chain-cloning $uri into $gcdir through $GIT_CACHE_SERVER"
-		git-cclone "$uri" "$edir" --mirror || error "chain-cloning failure"
+		info "cache miss - chain-cloning $uri into $gcdir through $GIT_CACHE_SERVER"
+		git-cclone "$uri" "$edir" --mirror >&2 || error "chain-cloning failure"
     else
-		info "cloning $uri into $gcdir"
+		info "cache miss - cloning $uri into $gcdir"
 		git clone --progress --mirror "$uri" "$edir" >&2 || error "cloning failure"
     fi
 else
     cd $gcdir
-    info "fetching $uri"
+    info "cache hit - refreshing cache from $uri"
     git fetch --progress >&2 || error "fetching failure"
 fi
 
